# Generated by Django 4.2.1 on 2023-06-01 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud1app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='email',
            field=models.EmailField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='user_name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
