# Generated by Django 4.2.1 on 2023-06-01 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud2app', '0002_post_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='user_name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
